[workspace]
members = [
    "libtiny_client",
    "libtiny_gui",
    "libtiny_logger",
    "libtiny_tui",
    "libtiny_ui",
    "libtiny_wire",
    "term_input",
    "termbox",
    "tiny",
]

[profile.release]
lto = true
